In [1]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap2.transforms import rot_z

print("Active z axis rotation")
Rz = np.transpose(rot_z(2*np.pi/3))
display(Rz)

Active z axis rotation


array([[-0.5      , -0.8660254,  0.       ],
       [ 0.8660254, -0.5      ,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [3]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap2.transforms import rot_x, rot_z

print("R = R_z(2pi/3) @ R_x(-pi/4)")
R = rot_z(2*np.pi/3) @ rot_x(-np.pi/4)
display(R)

R = R_z(2pi/3) @ R_x(-pi/4)


array([[-0.5       ,  0.61237244, -0.61237244],
       [-0.8660254 , -0.35355339,  0.35355339],
       [ 0.        ,  0.70710678,  0.70710678]])

In [8]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap2.transforms import rot_x, rot_y

R_a_to_b = rot_x(np.pi/6)
R_a_to_c = rot_y(np.pi/3)
R_d_to_c = rot_x(3*np.pi/4)

print("R_d^b = R_a_to_b*R_a_to_c^T*R_d_to_c")
R = R_a_to_b @ np.transpose(R_a_to_c) @ R_d_to_c
display(R)

R_d^b = R_a_to_b*R_a_to_c^T*R_d_to_c


array([[ 0.5       , -0.61237244, -0.61237244],
       [-0.4330127 , -0.78914913,  0.43559574],
       [-0.75      ,  0.04736717, -0.65973961]])

In [2]:
import numpy as np # Imports the numpy library and creates the alias np
from IPython.display import display # Used to display variables nicely in Jupyter
from mav_sim.chap3.mav_dynamics_euler import derivatives_euler, DynamicStateEuler, IND_EULER
from mav_sim.chap3.mav_dynamics import ForceMoments

# Define forces and moments
fm = ForceMoments()
fm.fx = 1
fm.fy = 2
fm.fz = 3
fm.l = 4
fm.m = 5
fm.n = 6

# Define the state
st = DynamicStateEuler(np.zeros((12,1)))
st.north = 7
st.east = 8
st.down = 9
st.u = 10
st.v = 11
st.w = 12
st.phi = np.pi/3
st.theta = np.pi/6
st.psi = np.pi/9
st.p = 13
st.q = 14
st.r = 15

# Define the time derivative
x_dot = derivatives_euler(state = st.convert_to_numpy(), forces_moments= fm.to_array())
# print("Time derivative")
# display(x_dot)
print("d/dt psi = ", x_dot.item(IND_EULER.PSI))
print("d/dt r = ", x_dot.item(IND_EULER.R))


d/dt psi =  22.660254037844386
d/dt r =  -52.35197118263826


In [ ]:
# Chapter 5
from mav_sim.chap3.mav_dynamics import DynamicState
from mav_sim.message_types.msg_sim_params import MsgSimParams
from mav_sim.chap2.mav_viewer import MavViewer
from mav_sim.chap3.data_viewer import DataViewer
from mav_sim.chap5.trim import compute_trim
from IPython.display import display # Used to display variables nicely in Jupyter

# Initialize state values
sim_params = MsgSimParams(end_time=40.)
state = DynamicState()

# Create the trim state
Va_trim = 25.
gamma_trim = 0.2
R = 800.
trim_state, trim_input = compute_trim(state.convert_to_numpy(), Va_trim, gamma_trim, R)

# Output the trim state and input
print("trim_state = ")
display(trim_state)
print("trim input = ")
trim_input.print()

In [ ]:
from mav_sim.chap6.pd_control_with_rate import PDControlWithRate

# PD control class:
pd = PDControlWithRate(kp=1.23, kd=4.56, limit=10.)

# Calculate update
#   error: 998.77
#   u prior to saturation: 1217.8167
#   u returned: 10.0
u_sat = pd.update(y_ref=2., y=1.23, ydot=2.34)

print("u_sat = ", u_sat)